stages:
  rules:
    - if:'$CI_PIPELINE_SOURCE == "push"'
  - test
  - build

build-image:
  stage: build
  name: xcyal/a-tracker
  entrypoint: [""]

test-running:
  stage: test
  script:
    - invoke test
