name: Build and push test container to Docker Hub

on:
  push:
    paths:
      - pyproject.toml
      - poetry.lock
      - Dockerfile
      - tasks.py
      - .github/workflows/docker.yaml
    branches:
      - main

  pull_request:
    paths:
      - pyproject.toml
      - poetry.lock
      - Dockerfile
      - tasks.py
      - .github/workflows/docker.yaml
    branches:
      - main
      - Objetivo-*-Ex

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log en Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extraer metadatos
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: xcyal/a-tracker
            
      - name: Construccion y push de imagen
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: xcyal/a-tracker
          labels: ${{ steps.meta.outputs.labels }}
